<a href="https://colab.research.google.com/github/gshashank84/learn-tf/blob/master/TF_issue_%2327150.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install tensorflow==2.0.0-alpha0 

    100% |████████████████████████████████| 79.9MB 411kB/s 
    100% |████████████████████████████████| 3.0MB 11.3MB/s 
    100% |████████████████████████████████| 61kB 23.3MB/s 
    100% |████████████████████████████████| 419kB 21.9MB/s 
  Found existing installation: tensorflow 1.13.1
    Uninstalling tensorflow-1.13.1:
      Successfully uninstalled tensorflow-1.13.1


In [2]:
import tensorflow as tf
tf.__version__

'2.0.0-alpha0'

In [16]:
m = tf.keras.metrics.MeanIoU(num_classes=2)
m.update_state(tf.convert_to_tensor([0, 0, 1, 1]), tf.convert_to_tensor([0, 1, 0, 1]))

  # cm = [[1, 1],
  #        [1, 1]]
  # sum_row = [2, 2], sum_col = [2, 2], true_positives = [1, 1]
  # iou = true_positives / (sum_row + sum_col - true_positives))
  # result = (1 / (2 + 2 - 1) + 1 / (2 + 2 - 1)) / 2 = 0.33
print('Final result: ', m.result().numpy())  # Final result: 0.33

W0326 16:40:15.266066 140191607879552 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/confusion_matrix.py:194: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0326 16:40:15.267881 140191607879552 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/confusion_matrix.py:195: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.


Final result:  0.33333334


In [8]:
tf.convert_to_tensor([[0,0,0,1],[1,1,1,1]]).shape.ndims

2

In [0]:
from tensorflow.python.framework import common_shapes
print(common_shapes.rank?

In [12]:
tf.random.normal((3,3)).shape.ndims

2

In [15]:
tf.convert_to_tensor([0, 0, 1, 1])

<tf.Tensor: id=33, shape=(4,), dtype=int32, numpy=array([0, 0, 1, 1], dtype=int32)>

In [0]:
from tensorflow.python.ops import array_ops
out = array_ops.reshape(tf.convert_to_tensor([0, 0, 1, 1]), [-1])

In [19]:
out.numpy()

array([0, 0, 1, 1], dtype=int32)

In [0]:
from tensorflow.python.framework import tensor_shape

In [33]:
tf.constant([1,1,0])

<tf.Tensor: id=114, shape=(3,), dtype=int32, numpy=array([1, 1, 0], dtype=int32)>

In [0]:
tf.convert_to_tensor??

In [35]:
m = tf.keras.metrics.BinaryAccuracy()
m.update_state([1, 1, 0, 0], [0.98, 1, 0, 0.6])
print('Final result: ', m.result().numpy())

Final result:  0.75


In [37]:
type(tf.constant([1,1]))

tensorflow.python.framework.ops.EagerTensor

In [38]:
type(tf.random.normal((3,3)))

tensorflow.python.framework.ops.EagerTensor

In [44]:
y_pred = tf.convert_to_tensor([1,1,1])
type(y_pred)

tensorflow.python.framework.ops.EagerTensor

In [43]:
if type(y_pred) != "tensorflow.python.framework.ops.EagerTensor":
  y_pred = tf.convert_to_tensor(y_pred)
  print("HUrray")

HUrray


In [0]:
tf.convert_to_tensor(y_pred)

In [51]:
y_pred = tf.random.normal((3,3))
y_pred

<tf.Tensor: id=192, shape=(3, 3), dtype=float32, numpy=
array([[ 0.2628391 ,  0.1370255 , -0.61660254],
       [ 0.23547073, -0.09118783,  1.2644624 ],
       [-0.9989397 ,  2.9207454 ,  1.0353811 ]], dtype=float32)>

In [49]:
array_ops.reshape(y_pred, [-1])

<tf.Tensor: id=179, shape=(9,), dtype=float32, numpy=
array([ 0.25083002,  0.47934282, -0.30556625,  1.2406862 , -0.7590226 ,
        0.23218057, -0.45146862,  0.81492394,  0.09444727], dtype=float32)>

In [54]:
tf.convert_to_tensor(tf.constant([3,3]))

<tf.Tensor: id=201, shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [0]:
tf.convert_to_tensor??

In [0]:
from tensorflow.python.framework import ops

In [58]:
ops.convert_to_tensor([1,1])

<tf.Tensor: id=203, shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [0]:
tf.rank??

In [64]:
tf.random.normal((3,3,3)).shape.ndims

3

In [67]:
tf.rank(tf.random.normal((3,3,3))).numpy()

3

In [0]:
from tensorflow.python.ops import array_ops

In [74]:
array_ops.rank([[1,2,3,4],[1,6,5,4]]).numpy()

2

In [78]:
y_true = [1,2,3]
array_ops.rank(y_true).numpy() >1

False

In [76]:
array_ops.rank(y_pred).numpy() > 1

True

In [80]:
1>1, y_pred.shape

(False, TensorShape([3, 3]))